server:
  port: 9000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://todowebapp.cucp3lnkiaxj.ap-northeast-2.rds.amazonaws.com:3306/todowebapp?serverTimezone=Asia/Seoul
    username: admin
    password: ENC(meT1ed+Syxr+7ccb8Yr/5OCmfe9CIDb/)

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: todo.web.app.project@gmail.com
    password: ENC(meT1ed+Syxr+7ccb8Yr/5OCmfe9CIDb/)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 827160312323-gfigf7lvp9n0ddq6423pueivp50gkgjg.apps.googleusercontent.com
            clientSecret: ENC(a1XPIzIp/ogJHiNdbW+E1DjduiJkS40ga50a+8Nkr1zKIJwtN8KJ4w==)
            scope: profile, email


